# Generated by Django 5.2.3 on 2025-08-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='id_arrival',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='vk_id',
        ),
        migrations.AddField(
            model_name='survey',
            name='show_answers',
            field=models.BooleanField(default=False),
        ),
    ]
