# Generated by Django 5.1 on 2024-11-02 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0002_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id_staff',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
