# Generated by Django 5.2.3 on 2025-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0002_remove_authuser_id_arrival_remove_authuser_vk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-03 23:11:11'),
            preserve_default=False,
        ),
    ]
