# Generated by Django 5.2.3 on 2025-09-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0003_survey_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUniqueView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_hash', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='askify_service.survey')),
            ],
            options={
                'unique_together': {('survey', 'view_hash')},
            },
        ),
        migrations.DeleteModel(
            name='SurveyView',
        ),
    ]
