# Generated by Django 5.1 on 2024-11-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0003_alter_authuser_id_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='id_staff',
            field=models.UUIDField(default='f56bb56c00f14a68ba5cda2af33958c3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswers',
            name='id_staff',
            field=models.UUIDField(default='f56bb56c00f14a68ba5cda2af33958c3'),
            preserve_default=False,
        ),
    ]
