# Generated by Django 5.2.3 on 2025-09-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0004_surveyuniqueview_delete_surveyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
