# Generated by Django 5.1 on 2024-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0004_survey_id_staff_useranswers_id_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.TextField(),
        ),
    ]
