# Generated by Django 5.1 on 2024-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0005_alter_survey_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='user_answers',
            field=models.TextField(),
        ),
    ]
