# Generated by Django 5.2.3 on 2025-10-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0006_survey_description_testattempt'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE askify_service_subscription ALTER COLUMN staff_id TYPE UUID USING staff_id::uuid;',
            reverse_sql='ALTER TABLE askify_service_subscription ALTER COLUMN staff_id TYPE TEXT;',
        ),
    ]

