# Generated by Django 5.2.3 on 2025-10-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0007_auto_20251002_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensused',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
