# Generated by Django 5.2.3 on 2025-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0008_alter_tokensused_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
