# Generated by Django 5.1 on 2024-11-05 08:13

import askify_service.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=64, unique=True)),
                ('amount', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=askify_service.utils.generate_payment_id, max_length=100, unique=True),
        ),
    ]
