# Generated by Django 5.1 on 2024-11-05 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0009_availablesubscription_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablesubscription',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availablesubscription',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free – 7 days'), ('standard', 'Standard – 30 days'), ('plus', 'Plus – 90 days')], default='free', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availablesubscription',
            name='plan_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
