# Generated by Django 5.2.3 on 2025-11-15 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0010_tag_survey_is_private_arenaprofile_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Внутреннее название для админки', max_length=255)),
                ('subject', models.CharField(help_text='Тема письма для Email', max_length=255)),
                ('message_body', models.TextField(help_text='Основной текст сообщения (HTML для Email, Markdown для Telegram)')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, max_length=500, null=True)),
                ('target_segment', models.CharField(choices=[('all', 'Всем пользователям'), ('active_subs', 'С активной подпиской'), ('inactive_subs', 'Без активной подписки'), ('no_tests', 'Кто не создал ни одного теста')], default='all', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Время начала фактической отправки', null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('processing', 'В процессе'), ('completed', 'Завершена')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='askify_service.mailing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mailing', 'user')},
            },
        ),
    ]
