# Generated by Django 5.2.3 on 2025-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0011_mailing_mailingrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Согласен ли пользователь получать рассылки'),
        ),
    ]
