# Generated by Django 5.2.3 on 2025-12-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0012_authuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='Мягкое удаление'),
        ),
    ]
