# Generated by Django 5.1 on 2024-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0012_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='id_staff',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
