# Generated by Django 5.1 on 2024-11-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0013_remove_useractivity_user_useractivity_id_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedusers',
            name='id_staff',
            field=models.UUIDField(blank=True, default='330a49ff31ab4ff8941b23c1c34acf01', unique=True),
            preserve_default=False,
        ),
    ]
