# Generated by Django 5.2.3 on 2025-12-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0013_survey_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='is_in_marketplace',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Подтверждено редакцией Летучки'),
        ),
    ]
