# Generated by Django 5.1 on 2024-11-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0014_blockedusers_id_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedusers',
            name='id_staff',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
