# Generated by Django 4.2.26 on 2026-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0015_magiclinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='test_balance',
            field=models.PositiveIntegerField(default=0, help_text='Пакеты тестов (не сгорают)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='questions_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
