# Generated by Django 5.1 on 2024-11-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0016_feedbackfromai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackfromai',
            old_name='staff_id',
            new_name='id_staff',
        ),
    ]
