# Generated by Django 5.1 on 2024-11-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0017_rename_staff_id_feedbackfromai_id_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='vk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
