# Generated by Django 5.1 on 2024-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0018_authuser_name_authuser_phone_authuser_vk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='tokens_used',
            field=models.IntegerField(default=991),
            preserve_default=False,
        ),
    ]
