# Generated by Django 4.2.26 on 2026-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0018_apikey_cost_and_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='generation_params',
            field=models.JSONField(blank=True, default=dict, help_text='Параметры генерации (сложность, типы вопросов и т.д.)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='source_text',
            field=models.TextField(blank=True, help_text='Исходный текст пользователя для перегенерации', null=True),
        ),
    ]
