# Generated by Django 5.1 on 2024-11-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0019_survey_tokens_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackfromai',
            name='tokens_used',
            field=models.IntegerField(default=993),
            preserve_default=False,
        ),
    ]
