# Generated by Django 5.1 on 2024-11-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0020_feedbackfromai_tokens_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokensUsed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_staff', models.UUIDField()),
                ('tokens_survey_used', models.IntegerField(default=0)),
                ('tokens_feedback_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackfromai',
            name='tokens_used',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tokens_used',
        ),
    ]
