# Generated by Django 5.1 on 2024-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0021_tokensused_remove_feedbackfromai_tokens_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensused',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-12 07:53:03.132679'),
            preserve_default=False,
        ),
    ]
