# Generated by Django 5.1 on 2024-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0023_payment_order_id_payment_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
        migrations.AddField(
            model_name='payment',
            name='staff_id',
            field=models.UUIDField(default='af928a9c8d2b44928907f3595f53c7e9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='staff_id',
            field=models.UUIDField(unique=True),
        ),
    ]
