# Generated by Django 5.1 on 2024-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0024_remove_payment_token_payment_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='confirmed_user',
            field=models.BooleanField(default=False),
        ),
    ]
