# Generated by Django 5.1 on 2024-12-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askify_service', '0024_remove_payment_token_payment_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='confirmed_user',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuthAdditionalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.IntegerField(blank=True, null=True)),
                ('id_vk', models.IntegerField(blank=True, null=True)),
                ('id_yandex', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
